### PR TITLE
Add exclude_encoder parameter

### PR DESCRIPTION
**Pull request by drnextgis**
We discovered that Brotli in some circumstances works much slower compared to other encoders but at the moment there is no way to disable it. This PR makes it possible.

### CODE REVIEW

**Comment by vincentsarago** [comment]
Oh no!!! this is really weird, can you describe the `circumstances` ?

**Comment by vincentsarago** [comment]
FYI test are failing on the pre-commit step because of a bad configuration, I'll fix this tomorrow and cut a new release. 

That's said I would love to know the circumstances so we can pass feedback upstream

**Comment by drnextgis** [comment]
We suspect that it might be due to the lack of Lambda's resources where `stac-fastapi` is running. Currently it only has 128MB.

```
$ curl -s -o /dev/null -w 'Total: %{time_total}s\n' 'https://***/stac/search' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'Authorization: Bearer ...'\
  -H 'content-type: application/json' \
  -H 'accept-encoding: br' \
  --data-raw '{"collections":["l1"],"maxPrice":72,"clouds":0,"datetime":"2022-05-01T00:00:00Z/2022-06-01T23:59:59Z","bbox":[-145.73363431151242,-79.37926194134536,145.73363431151242,79.37926194134533],"limit":100}' \
  --compressed
Total: 9.996264s

$ curl -s -o /dev/null -w 'Total: %{time_total}s\n' 'https://***/stac/search' \
  -H 'accept: application/json, text/plain, */*' \
  -H 'accept-language: en-US,en;q=0.9' \
  -H 'Authorization: Bearer ...' \
  -H 'content-type: application/json' \
  -H 'accept-encoding: deflate' \
  --data-raw '{"collections":["l1"],"maxPrice":72,"clouds":0,"datetime":"2022-05-01T00:00:00Z/2022-06-01T23:59:59Z","bbox":[-145.73363431151242,-79.37926194134536,145.73363431151242,79.37926194134533],"limit":100}' \
  --compressed
Total: 1.178740s
```

**Comment by vincentsarago** [comment]
🙏 thanks @drnextgis I'll merge / update the changelog / cut a 0.2.0 release

**Comment by vincentsarago** [comment]
I've tried to reproduce this with a simple app 

<details>

```python
"""AWS Lambda handler."""

import os
import time

from mangum import Mangum
from fastapi import FastAPI, Query

from starlette.middleware.base import BaseHTTPMiddleware
from starlette.requests import Request
from starlette.types import ASGIApp
from starlette_cramjam.middleware import CompressionMiddleware


class TotalTimeMiddleware(BaseHTTPMiddleware):
    """MiddleWare to add Total process time in response headers."""

    async def dispatch(self, request: Request, call_next):
        """Add X-Process-Time."""
        start_time = time.time()
        response = await call_next(request)
        process_time = time.time() - start_time
        timings = response.headers.get("Server-Timing")
        app_time = "total;dur={}".format(round(process_time * 1000, 2))
        print(response.headers)
        response.headers["Server-Timing"] = (
            f"{timings}, {app_time}" if timings else app_time
        )
        return response



app = FastAPI()
app.add_middleware(CompressionMiddleware, minimum_size=0)
app.add_middleware(TotalTimeMiddleware)


@app.get("/")
def landing():
    return {"hey": "Yo"}


@app.get("/json")
def json_resp(n: int = Query(0)):
    return {
        "type": "FeatureCollection",
        "features": (
            {
                "type": "Feature",
                "properties": {},
                "geometry": {
                    "type": "Polygon",
                    "coordinates": [
                        [
                            [-57.3486328125, 72.25226599952339],
                            [-57.041015625, 72.1279362810559],
                            [-56.722412109375, 72.06038062953813],
                            [-54.86572265625, 72.07052969916067],
                            [-54.613037109375, 72.63665259171732],
                            [-56.14013671875, 72.90995232978632],
                            [-57.3486328125, 72.25226599952339],
                        ]
                    ],
                },
            },
        ) * n
    }




handler = Mangum(app, lifespan="auto")
```

</details>

I added `TotalTimeMiddleware` to check the `processing` time on the lambda to make sure the timing difference didn't come from `uncompressing` the data 


```
$ time httpx https://30wsbcvetk.execute-api.us-east-1.amazonaws.com/json\?n\=1000 -h Accept-Encoding br --download /dev/null
HTTP/1.1 200 OK
Date: Mon, 06 Jun 2022 19:15:33 GMT
Content-Type: application/json
Content-Length: 204
Connection: keep-alive
content-encoding: br
vary: Accept-Encoding
Server-Timing: total;dur=1687.17
0.20s user 0.03s system 9% cpu 2.397 total

$ time httpx https://30wsbcvetk.execute-api.us-east-1.amazonaws.com/json\?n\=1000 -h Accept-Encoding gzip --download /dev/null
HTTP/1.1 200 OK
Date: Mon, 06 Jun 2022 19:15:42 GMT
Content-Type: application/json
Content-Length: 1718
Connection: keep-alive
content-encoding: gzip
vary: Accept-Encoding
Server-Timing: total;dur=1246.26
0.20s user 0.04s system 11% cpu 2.052 total
```

This kinda confirms that `br` is slower by 400ms ... while for your example was 8 seconds slower 😱.

**Pull request merged**
